export class Version {
    static VERSION = "4.6.6a-2957aea" //SCRIPT_SPECIAL_TOKEN_REPLACE_GITVERSION
    static TIMESTAMP = "9/28/2026 00:10:29" //SCRIPT_SPECIAL_TOKEN_REPLACE_GITTIMESTAMP
    static PATCHWORK_VERSION = "1.3.2-beta"
}