export class Version {
    static VERSION = "4.8.0a-d9547ca" //SCRIPT_SPECIAL_TOKEN_REPLACE_GITVERSION
    static TIMESTAMP = "9/29/2026 21:03:09" //SCRIPT_SPECIAL_TOKEN_REPLACE_GITTIMESTAMP
    static PATCHWORK_VERSION = "1.3.2-beta"
}